### ISSUE TITLE
ModuleNotFoundError: No module named 'multimatch'

### ISSUE THREAD

**Issue by oliver-contier** [AdinaWagner/multimatch#9]
Installation problems on MacOS Mojave (10.14.2), Anaconda virtual env (python 3.6.7)

`
$ which python
/Users/Oliver/anaconda2/envs/adinatest/bin/python

$ python --version
Python 3.6.7 :: Anaconda, Inc.
`

calling multimatch in command line yields:

`
$ multimatch
Traceback (most recent call last):
  File "/Users/Oliver/anaconda2/envs/adinatest/bin/multimatch", line 7, in <module>
    from multimatch.multimatch import main
ModuleNotFoundError: No module named 'multimatch'`

importing multimatch from ipython yields:

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-03708941dec5> in <module>
----> 1 import multimatch

ModuleNotFoundError: No module named 'multimatch'`

**Comment by AdinaWagner** [comment]
Sorry to bug you again - I had an epiphany yesterday night: could you check whether the ipython you are using actually comes from your newly created virtual env? If the package is installed in the venv, but ipython comes from out of the venv, ipython can't find anything... (or so I assume?)

could you either...:
- install multimatch AND ipython inside your venv (maybe check 'which ipython' to see where it comes from - should be path to your venv)
- install multimatch inside your venv and open plain python in a shell instead of ipython (maybe check 'which python', should also be path to your venv)
- install multimatch outside of a venv (I'm 99% sure that this can't break anything... i hope...) :P

**Comment by yarikoptic** [comment]
FWIW, ipython a sneaky thing topically detects that it is running with python coming from a virtual environment... But I don't even see Oliver mentioning ipython

**Comment by oliver-contier** [comment]
```
(adinatest)  ~  which python
/Users/Oliver/anaconda2/envs/adinatest/bin/python
```

Still occurs when trying to import in a plain python shell. 

```
(adinatest)  ✘  ~  python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import multimatch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'multimatch'
>>> quit()
(adinatest)  ~ 
```

Also I think the error from when I try to call it from the command line directly points to an actual line in your package. Maybe that's a starting piont for you? ;-)

```
(adinatest)  ~  multimatch
Traceback (most recent call last):
  File "/Users/Oliver/anaconda2/envs/adinatest/bin/multimatch", line 7, in <module>
    from multimatch.multimatch import main
ModuleNotFoundError: No module named 'multimatch'

```

**Comment by oliver-contier** [comment]
By the way. The script that is pointed to is the only sign of multimatch in that anaconda environment's bin. And it contians the following:

```
(adinatest)  ~  cd /Users/Oliver/anaconda2/envs/adinatest/bin/
(adinatest)  ~/anaconda2/envs/adinatest/bin  ls
2to3              lzcat             openssl           pyvenv-3.6        wheel
2to3-3.6          lzcmp             pip               reset             wish
c_rehash          lzdiff            pydoc             sqlite3           wish8.6
captoinfo         lzegrep           pydoc3            sqlite3_analyzer  xz
clear             lzfgrep           pydoc3.6          tabs              xzcat
easy_install      lzgrep            python            tclsh             xzcmp
f2py              lzless            python3           tclsh8.6          xzdec
f2py3             lzma              python3-config    tic               xzdiff
f2py3.6           lzmadec           python3.6         toe               xzegrep
idle3             lzmainfo          python3.6-config  tput              xzfgrep
idle3.6           lzmore            python3.6m        tset              xzgrep
infocmp           multimatch        python3.6m-config unlzma            xzless
infotocap         ncursesw6-config  pyvenv            unxz              xzmore
(adinatest)  ~/anaconda2/envs/adinatest/bin  cat multimatch
#!/Users/Oliver/anaconda2/envs/adinatest/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from multimatch.multimatch import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Maybe it has to do with anaconda specifics. I don't currently have virtualenv installed...

**Comment by AdinaWagner** [comment]
Thanks for trying anyway, Oli :)

> Also I think the error from when I try to call it from the command line directly points to an actual line in your package. Maybe that's a starting piont for you? ;-)

Well, its not surprising that it tries to import main(), because this is what it should do for this entrypoint - its just surprising that it fails. I finally got some basic tests with appveyor and circleci set up which pass for non-Linux operating systems - so the code seems to be working, just the import doesn't. I bet thats because I do not yet fully comprehend how imports work internally - whenever I don't understand something I manage to get it to crash. I will read the setup tools documentation start to end once I have a day to spare, and also read up on relative and absolute imports. Much to learn I have!

thanks again and sorry I keep bothering you with this!
